-- MySQL Script generated by MySQL Workbench
-- Thu Dec 12 20:42:19 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema myinventory
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema myinventory
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `myinventory` DEFAULT CHARACTER SET utf8 ;
USE `myinventory` ;

-- -----------------------------------------------------
-- Table `myinventory`.`Inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myinventory`.`Inventory` (
  `inventoryID` INT NOT NULL AUTO_INCREMENT,
  `organizationName` VARCHAR(100) NOT NULL,
  `organizationDescription` VARCHAR(200) NULL,
  PRIMARY KEY (`inventoryID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myinventory`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myinventory`.`Users` (
  `userID` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(80) NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  `email` VARCHAR(100) NULL,
  `organizationID` INT NULL,
  `memberType` VARCHAR(10) NULL,
  PRIMARY KEY (`userID`, `userName`, `password`),
  UNIQUE INDEX `userID_UNIQUE` (`userID` ASC) VISIBLE,
  UNIQUE INDEX `userName_UNIQUE` (`userName` ASC) VISIBLE,
  CONSTRAINT `fk_Users_Inventory1`
    FOREIGN KEY (`organizationID`)
    REFERENCES `myinventory`.`Inventory` (`inventoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myinventory`.`Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myinventory`.`Items` (
  `itemID` INT NOT NULL AUTO_INCREMENT,
  `itemName` VARCHAR(100) NOT NULL,
  `itemDescription` TEXT NULL,
  `itemCount` INT NOT NULL DEFAULT 1,
  `inventoryID` INT NOT NULL,
  PRIMARY KEY (`itemID`, `itemName`),
  CONSTRAINT `fk_Items_Inventory2`
    FOREIGN KEY (`inventoryID`)
    REFERENCES `myinventory`.`Inventory` (`inventoryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `myinventory`.`Authentication`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myinventory`.`Authentication` (
  `authToken` VARCHAR(45) NOT NULL,
  `userID` INT NOT NULL,
  PRIMARY KEY (`authToken`),
  INDEX `fk_Authentication_Users1_idx` (`userID` ASC) VISIBLE,
  UNIQUE INDEX `authToken_UNIQUE` (`authToken` ASC) VISIBLE,
  CONSTRAINT `fk_Authentication_Users1`
    FOREIGN KEY (`userID`)
    REFERENCES `myinventory`.`Users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
